# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: capstone
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  MYSQL_DATABASE: challengedb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword123